# Generated by Django 3.2.7 on 2023-06-20 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegramemail', '0002_auto_20230620_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailmessage',
            old_name='to_email',
            new_name='recipient',
        ),
    ]
