# Generated by Django 3.2.7 on 2023-06-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramemail', '0003_rename_to_email_emailmessage_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
