# Generated by Django 3.2.7 on 2023-06-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramemail', '0004_auto_20230620_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('recipient', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
