# Generated by Django 4.2.2 on 2023-07-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramemail', '0006_alter_emailmessage_body_alter_emailmessage_recipient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
